/**
 * AUTO GENERATED by Supabase schema introspection
 * Generated: 2026-03-19
 *
 * This file defines all table types used in the Meta Ads Manager application.
 * Ensures type safety for Supabase queries with full TypeScript support.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      // === Core User Tables ===
      users: {
        Row: {
          id: string;
          email: string;
          full_name: string | null;
          avatar_url: string | null;
          // Meta connection fields (nullable for backward compatibility)
          meta_access_token: string | null;
          meta_token_expires_at: string | null;
          meta_user_id: string | null;
          meta_user_name: string | null;
          meta_connected_at: string | null;
          meta_scopes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          full_name?: string | null;
          avatar_url?: string | null;
          meta_access_token?: string | null;
          meta_token_expires_at?: string | null;
          meta_user_id?: string | null;
          meta_user_name?: string | null;
          meta_connected_at?: string | null;
          meta_scopes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          full_name?: string | null;
          avatar_url?: string | null;
          meta_access_token?: string | null;
          meta_token_expires_at?: string | null;
          meta_user_id?: string | null;
          meta_user_name?: string | null;
          meta_connected_at?: string | null;
          meta_scopes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };

      // === OAuth State Management ===
      oauth_states: {
        Row: {
          id: string;
          state: string;
          provider: 'meta' | 'google';
          user_id: string;
          expires_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          state: string;
          provider: 'meta' | 'google';
          user_id: string;
          expires_at: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          state?: string;
          provider?: 'meta' | 'google';
          user_id?: string;
          expires_at?: string;
          created_at?: string;
        };
        Relationships: [];
      };

      // === OAuth Connection Tables ===
      meta_connections: {
        Row: {
          id: string;
          user_id: string;
          meta_user_id: string;
          meta_user_name: string;
          meta_access_token: string;
          meta_token_expires_at: string | null;
          meta_scopes: string;
          connection_status: 'active' | 'revoked' | 'expired';
          created_at: string;
          updated_at: string;
          last_used_at: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          meta_user_id: string;
          meta_user_name: string;
          meta_access_token: string;
          meta_token_expires_at?: string | null;
          meta_scopes: string;
          connection_status?: 'active' | 'revoked' | 'expired';
          created_at?: string;
          updated_at?: string;
          last_used_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          meta_user_id?: string;
          meta_user_name?: string;
          meta_access_token?: string;
          meta_token_expires_at?: string | null;
          meta_scopes?: string;
          connection_status?: 'active' | 'revoked' | 'expired';
          created_at?: string;
          updated_at?: string;
          last_used_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'meta_connections_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          }
        ];
      };

      // === Meta Accounts & Access Control ===
      meta_accounts: {
        Row: {
          id: string;
          user_id: string;
          meta_account_id: string;
          meta_account_name: string;
          currency?: string;
          timezone?: string;
          last_synced?: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          meta_account_id: string;
          meta_account_name: string;
          currency?: string;
          timezone?: string;
          last_synced?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          meta_account_id?: string;
          meta_account_name?: string;
          currency?: string;
          timezone?: string;
          last_synced?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };

      user_account_access: {
        Row: {
          id: string;
          user_id: string;
          account_id: string;
          access_level: 'owner' | 'editor' | 'viewer';
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          account_id: string;
          access_level: 'owner' | 'editor' | 'viewer';
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          account_id?: string;
          access_level?: 'owner' | 'editor' | 'viewer';
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };

      // === Campaign Objects ===
      campaigns: {
        Row: {
          id: string;
          user_id: string;
          account_id: string;
          meta_campaign_id: string | null;
          name: string;
          objective: string;
          status: 'ACTIVE' | 'PAUSED' | 'DRAFT';
          daily_budget: number | null;
          lifetime_budget: number | null;
          budget_type: 'daily' | 'lifetime';
          start_time: string | null;
          stop_time: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          account_id: string;
          meta_campaign_id?: string | null;
          name: string;
          objective: string;
          status?: 'ACTIVE' | 'PAUSED' | 'DRAFT';
          daily_budget?: number | null;
          lifetime_budget?: number | null;
          budget_type?: 'daily' | 'lifetime';
          start_time?: string | null;
          stop_time?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          account_id?: string;
          meta_campaign_id?: string | null;
          name?: string;
          objective?: string;
          status?: 'ACTIVE' | 'PAUSED' | 'DRAFT';
          daily_budget?: number | null;
          lifetime_budget?: number | null;
          budget_type?: 'daily' | 'lifetime';
          start_time?: string | null;
          stop_time?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };

      meta_ads_campaigns: {
        Row: {
          id: string;
          campaign_id: string;
          meta_campaign_id: string;
          synced_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          campaign_id: string;
          meta_campaign_id: string;
          synced_at?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          campaign_id?: string;
          meta_campaign_id?: string;
          synced_at?: string;
          created_at?: string;
        };
        Relationships: [];
      };

      // === Ad Set Objects ===
      meta_ad_sets: {
        Row: {
          id: string;
          campaign_id: string;
          meta_adset_id: string;
          name: string;
          status: 'ACTIVE' | 'PAUSED' | 'DRAFT';
          daily_budget: number | null;
          lifetime_budget: number | null;
          billing_event: string;
          bid_strategy: string;
          bid_amount: number | null;
          targeting: Json | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          campaign_id: string;
          meta_adset_id: string;
          name: string;
          status?: 'ACTIVE' | 'PAUSED' | 'DRAFT';
          daily_budget?: number | null;
          lifetime_budget?: number | null;
          billing_event: string;
          bid_strategy: string;
          bid_amount?: number | null;
          targeting?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          campaign_id?: string;
          meta_adset_id?: string;
          name?: string;
          status?: 'ACTIVE' | 'PAUSED' | 'DRAFT';
          daily_budget?: number | null;
          lifetime_budget?: number | null;
          billing_event?: string;
          bid_strategy?: string;
          bid_amount?: number | null;
          targeting?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };

      // === Ad Objects ===
      meta_ads: {
        Row: {
          id: string;
          adset_id: string;
          meta_ad_id: string;
          name: string;
          status: 'ACTIVE' | 'PAUSED' | 'DRAFT';
          creative_headline: string;
          creative_body: string;
          creative_url: string;
          creative_image_url: string | null;
          creative_video_url: string | null;
          creative_format: 'single_image' | 'single_video' | 'carousel' | 'collection';
          page_id: string | null;
          pixel_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          adset_id: string;
          meta_ad_id: string;
          name: string;
          status?: 'ACTIVE' | 'PAUSED' | 'DRAFT';
          creative_headline: string;
          creative_body: string;
          creative_url: string;
          creative_image_url?: string | null;
          creative_video_url?: string | null;
          creative_format: 'single_image' | 'single_video' | 'carousel' | 'collection';
          page_id?: string | null;
          pixel_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          adset_id?: string;
          meta_ad_id?: string;
          name?: string;
          status?: 'ACTIVE' | 'PAUSED' | 'DRAFT';
          creative_headline?: string;
          creative_body?: string;
          creative_url?: string;
          creative_image_url?: string | null;
          creative_video_url?: string | null;
          creative_format?: 'single_image' | 'single_video' | 'carousel' | 'collection';
          page_id?: string | null;
          pixel_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };

      // === Meta Assets ===
      meta_pages: {
        Row: {
          id: string;
          account_id: string;
          meta_page_id: string;
          page_name: string;
          page_category: string | null;
          synced_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          account_id: string;
          meta_page_id: string;
          page_name: string;
          page_category?: string | null;
          synced_at?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          account_id?: string;
          meta_page_id?: string;
          page_name?: string;
          page_category?: string | null;
          synced_at?: string;
          created_at?: string;
        };
        Relationships: [];
      };

      meta_pixels: {
        Row: {
          id: string;
          account_id: string;
          meta_pixel_id: string;
          pixel_name: string;
          synced_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          account_id: string;
          meta_pixel_id: string;
          pixel_name: string;
          synced_at?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          account_id?: string;
          meta_pixel_id?: string;
          pixel_name?: string;
          synced_at?: string;
          created_at?: string;
        };
        Relationships: [];
      };

      // === Google Ads Integration ===
      google_ads_accounts: {
        Row: {
          id: string;
          user_id: string;
          google_customer_id: string;
          account_name: string;
          currency_code: string | null;
          time_zone: string | null;
          last_synced: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          google_customer_id: string;
          account_name: string;
          currency_code?: string | null;
          time_zone?: string | null;
          last_synced?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          google_customer_id?: string;
          account_name?: string;
          currency_code?: string | null;
          time_zone?: string | null;
          last_synced?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };

      google_ads_campaigns: {
        Row: {
          id: string;
          google_account_id: string;
          campaign_id: string;
          google_campaign_id: string;
          synced_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          google_account_id: string;
          campaign_id: string;
          google_campaign_id: string;
          synced_at?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          google_account_id?: string;
          campaign_id?: string;
          google_campaign_id?: string;
          synced_at?: string;
          created_at?: string;
        };
        Relationships: [];
      };

      // === Notifications & Alerts ===
      meta_notifications: {
        Row: {
          id: string;
          user_id: string;
          account_id: string | null;
          type: 'info' | 'warning' | 'error' | 'success';
          title: string;
          message: string;
          is_read: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          account_id?: string | null;
          type: 'info' | 'warning' | 'error' | 'success';
          title: string;
          message: string;
          is_read?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          account_id?: string | null;
          type?: 'info' | 'warning' | 'error' | 'success';
          title?: string;
          message?: string;
          is_read?: boolean;
          created_at?: string;
        };
        Relationships: [];
      };

      meta_alert_rules: {
        Row: {
          id: string;
          user_id: string;
          account_id: string;
          rule_type: string;
          condition: string;
          threshold: number | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          account_id: string;
          rule_type: string;
          condition: string;
          threshold?: number | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          account_id?: string;
          rule_type?: string;
          condition?: string;
          threshold?: number | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };

      // === Logging & Sync ===
      sync_log: {
        Row: {
          id: string;
          user_id: string;
          account_id: string;
          sync_type: string;
          status: 'pending' | 'success' | 'failed';
          error_message: string | null;
          synced_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          account_id: string;
          sync_type: string;
          status: 'pending' | 'success' | 'failed';
          error_message?: string | null;
          synced_at?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          account_id?: string;
          sync_type?: string;
          status?: 'pending' | 'success' | 'failed';
          error_message?: string | null;
          synced_at?: string;
          created_at?: string;
        };
        Relationships: [];
      };

      access_logs: {
        Row: {
          id: string;
          user_id: string;
          action: string;
          resource: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          action: string;
          resource: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          action?: string;
          resource?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      publish_jobs: {
        Row: {
          id: string;
          user_id: string;
          status: 'pending' | 'running' | 'completed' | 'partial' | 'failed';
          total_campaigns: number;
          completed_campaigns: number;
          results: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          status?: 'pending' | 'running' | 'completed' | 'partial' | 'failed';
          total_campaigns?: number;
          completed_campaigns?: number;
          results?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          status?: 'pending' | 'running' | 'completed' | 'partial' | 'failed';
          total_campaigns?: number;
          completed_campaigns?: number;
          results?: Json;
          updated_at?: string;
        };
        Relationships: [];
      };
      meta_insights: {
        Row: {
          id: string;
          meta_account_id: string;
          object_id: string;
          object_type: 'campaign' | 'adset' | 'ad';
          date_start: string;
          date_stop: string;
          impressions: number;
          clicks: number;
          spend_micros: number;
          cpc_micros: number | null;
          cpm_micros: number | null;
          ctr: number | null;
          inline_link_clicks: number;
          landing_page_views: number;
          actions: Json | null;
          action_values: Json | null;
          conversions: number;
          roas: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          meta_account_id: string;
          object_id: string;
          object_type: 'campaign' | 'adset' | 'ad';
          date_start: string;
          date_stop: string;
          impressions?: number;
          clicks?: number;
          spend_micros?: number;
          cpc_micros?: number | null;
          cpm_micros?: number | null;
          ctr?: number | null;
          inline_link_clicks?: number;
          landing_page_views?: number;
          actions?: Json | null;
          action_values?: Json | null;
          conversions?: number;
          roas?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          impressions?: number;
          clicks?: number;
          spend_micros?: number;
          cpc_micros?: number | null;
          cpm_micros?: number | null;
          ctr?: number | null;
          inline_link_clicks?: number;
          landing_page_views?: number;
          actions?: Json | null;
          action_values?: Json | null;
          conversions?: number;
          roas?: number | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      meta_sync_status: {
        Row: {
          id: string;
          meta_account_id: string;
          sync_type: 'campaigns' | 'adsets' | 'ads' | 'insights';
          last_synced_at: string | null;
          last_sync_status: 'pending' | 'running' | 'success' | 'partial' | 'failed';
          last_error: string | null;
          records_synced: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          meta_account_id: string;
          sync_type: 'campaigns' | 'adsets' | 'ads' | 'insights';
          last_synced_at?: string | null;
          last_sync_status?: 'pending' | 'running' | 'success' | 'partial' | 'failed';
          last_error?: string | null;
          records_synced?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          last_synced_at?: string | null;
          last_sync_status?: 'pending' | 'running' | 'success' | 'partial' | 'failed';
          last_error?: string | null;
          records_synced?: number;
          updated_at?: string;
        };
        Relationships: [];
      };
    };
    Views: {};
    Functions: {};
    Enums: {};
    CompositeTypes: {};
  };
};
