/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx}',
    './src/components/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      fontFamily: {
        sans:    ['Inter', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'sans-serif'],
        mono:    ['IBM Plex Mono', 'SF Mono', 'monospace'],
        display: ['Inter', 'system-ui', 'sans-serif'],
      },
      colors: {
        'color-bg-base':          '#09090b',
        'color-bg-surface':       '#18181b',
        'color-bg-surface-hover': '#27272a',
        'color-bg-input':         '#27272a',
        'color-bg-sidebar':       '#09090b',
        'color-bg-popover':       '#18181b',
        'color-bg-row-hover':     '#1f1f23',

        'color-text-primary':     '#fafafa',
        'color-text-secondary':   '#a1a1aa',
        'color-text-tertiary':    '#71717a',
        'color-text-disabled':    '#52525b',

        'color-accent':           '#16a34a',
        'color-accent-dim':       '#15803d',
        'color-accent-bright':    '#22c55e',
        'color-accent-dark':      '#16a34a',

        'color-success':  '#22c55e',
        'color-warning':  '#eab308',
        'color-danger':   '#ef4444',
        'color-info':     '#3b82f6',

        // Legacy aliases
        'neon-green':   { DEFAULT: '#16a34a', dim: '#15803d', bright: '#22c55e' },
        'neon-cyan':    { DEFAULT: '#00f0ff' },
        'neon-magenta': { DEFAULT: '#ef4444' },
        'neon-amber':   { DEFAULT: '#eab308' },
        'neon-purple':  { DEFAULT: '#a100f2' },
        'bg-deepest':   '#09090b',
        'bg-page':      '#09090b',
        'bg-sidebar':   '#09090b',
        'bg-card':      '#18181b',
        'bg-card-hover':'#27272a',
        'bg-input':     '#27272a',
        'bg-row-hover': '#1f1f23',
        'bg-popover':   '#18181b',
        'text-primary':   '#fafafa',
        'text-secondary': '#a1a1aa',
        'text-tertiary':  '#71717a',
        'success':        '#22c55e',
        'warning':        '#eab308',
        'danger':         '#ef4444',
        'info':           '#3b82f6',
      },
      boxShadow: {
        card:         '0 1px 3px rgba(0,0,0,0.5), 0 0 0 1px rgba(255,255,255,0.04)',
        'card-hover': '0 4px 16px rgba(0,0,0,0.5)',
        elevated:     '0 8px 32px rgba(0,0,0,0.6), 0 0 0 1px rgba(255,255,255,0.06)',
        focus:        '0 0 0 3px rgba(22,163,74,0.25)',
        'accent':     '0 0 12px rgba(22,163,74,0.25)',
      },
      borderRadius: {
        sm:   '6px',
        md:   '8px',
        lg:   '12px',
        xl:   '16px',
        pill: '100px',
        // Legacy
        card:  '12px',
        modal: '12px',
      },
      fontSize: {
        '2xs': ['10px', { lineHeight: '14px' }],
        xs:    ['11px', { lineHeight: '16px' }],
        sm:    ['12px', { lineHeight: '18px' }],
        base:  ['13px', { lineHeight: '20px' }],
        md:    ['14px', { lineHeight: '20px' }],
        lg:    ['16px', { lineHeight: '24px' }],
        xl:    ['18px', { lineHeight: '26px' }],
        '2xl': ['22px', { lineHeight: '30px' }],
        '3xl': ['28px', { lineHeight: '36px' }],
      },
      transitionTimingFunction: {
        spring: 'cubic-bezier(0.16, 1, 0.3, 1)',
      },
    },
  },
  plugins: [],
  darkMode: ['class', '[data-theme="dark"]'],
};
